# Generated by Django 5.1.4 on 2025-01-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=155)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('user_password', models.CharField(max_length=55)),
                ('user_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('user_dob', models.DateField(blank=True, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=15, null=True)),
                ('user_ack', models.BooleanField(blank=True, default=1, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_passphrase', models.CharField(blank=True, max_length=100, null=True)),
                ('user_signal_on', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Access_Token',
            fields=[
                ('user_preference', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user')),
            ],
            options={
                'db_table': 'Access_Token',
            },
        ),
        migrations.CreateModel(
            name='User_Preference',
            fields=[
                ('user_preference', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('order_size', models.IntegerField(blank=True, max_length=100, null=True)),
                ('time_in_force', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user')),
            ],
            options={
                'db_table': 'User_Preference',
            },
        ),
    ]
