# Generated by Django 5.1.5 on 2025-01-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calender_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Datetimee', models.DateTimeField(blank=True, null=True)),
                ('Event_Start', models.DateTimeField(blank=True, null=True)),
                ('Event_End', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('impact', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'calender_data',
            },
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=155)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('user_password', models.CharField(max_length=55)),
                ('user_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('user_dob', models.DateField(blank=True, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=15, null=True)),
                ('user_ack', models.BooleanField(blank=True, default=1, null=True)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_passphrase', models.CharField(blank=True, max_length=100, null=True)),
                ('user_signal_on', models.BooleanField(default=0)),
                ('user_tradingview_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Userdata',
            },
        ),
        migrations.CreateModel(
            name='User_Preference',
            fields=[
                ('user_preference', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('order_size', models.IntegerField(blank=True, null=True)),
                ('time_in_force', models.CharField(blank=True, max_length=100, null=True)),
                ('order_type', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.userdata')),
            ],
            options={
                'db_table': 'User_Preference',
            },
        ),
        migrations.CreateModel(
            name='multiple_take_profit_orders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_id', models.BigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.userdata')),
            ],
            options={
                'db_table': 'multiple_take_profit_orders',
            },
        ),
        migrations.CreateModel(
            name='calender_impact_selection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Holiday', models.BooleanField(blank=True, default=1, null=True)),
                ('Low', models.BooleanField(blank=True, default=1, null=True)),
                ('High', models.BooleanField(blank=True, default=1, null=True)),
                ('Medium', models.BooleanField(blank=True, default=1, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.userdata')),
            ],
            options={
                'db_table': 'calender_impact_selection',
            },
        ),
        migrations.CreateModel(
            name='Access_Token',
            fields=[
                ('Access_Token_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiry_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.userdata')),
            ],
            options={
                'db_table': 'Access_Token',
            },
        ),
    ]
