# Generated by Django 5.1.4 on 2025-01-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preference',
            name='order_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
