# Generated by Django 5.1.4 on 2025-01-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_preference',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_preference',
            name='order_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
