# Generated by Django 5.1.4 on 2025-01-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_user_preference_account_user_preference_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_tradingview_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
