# Generated by Django 5.1.4 on 2025-01-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_alter_user_preference_order_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_token',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='access_token',
            name='expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='access_token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
