# Generated by Django 5.1.4 on 2025-01-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_user_user_tradingview_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdata',
        ),
        migrations.AlterModelTable(
            name='userdata',
            table='Userdata',
        ),
    ]
