# Generated by Django 5.1.4 on 2025-01-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_rename_user_userdata_alter_userdata_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access_token',
            old_name='user_preference',
            new_name='Access_Token_id',
        ),
    ]
