# Generated by Django 5.1.4 on 2025-01-15 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_rename_user_preference_access_token_access_token_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='multiple_take_profit_orders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_id', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.userdata')),
            ],
            options={
                'db_table': 'multiple_take_profit_orders',
            },
        ),
    ]
