# Generated by Django 5.1.4 on 2025-01-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_multiple_take_profit_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_take_profit_orders',
            name='order_id',
            field=models.BigIntegerField(),
        ),
    ]
