# Generated by Django 5.1.4 on 2025-01-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0007_alter_multiple_take_profit_orders_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='calender_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Datetimee', models.DateTimeField(blank=True, null=True)),
                ('Event_Start', models.DateTimeField(blank=True, null=True)),
                ('Event_End', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('impact', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'calender_data',
            },
        ),
    ]
