# Generated by Django 5.1.4 on 2025-01-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_calender_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='calender_impact_selection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Holiday', models.BooleanField(blank=True, default=1, null=True)),
                ('Low', models.BooleanField(blank=True, default=1, null=True)),
                ('High', models.BooleanField(blank=True, default=1, null=True)),
                ('Medium', models.BooleanField(blank=True, default=1, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.userdata')),
            ],
            options={
                'db_table': 'calender_impact_selection',
            },
        ),
    ]
